# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "cdf0f0c71c08660e3e9a1b73312ca969"
name = "checkout-ext-learning-04"
handle = "checkout-ext-learning-04"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
dev_store_url = "shahrukh-checkout-ext.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_delivery_customizations"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[webhooks]
api_version = "2024-10"

[pos]
embedded = false
